server:
    port: 1080
logging:
  path: /usr/local/jars/log/${spring.application.name}
spring:
  application:
    name: weather-report

  thymeleaf:
    cache: false
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    prefix: classpath:/templates
    suffix: .html

